### ISSUE TITLE
当.livep文件里面包含的是.heic等类型的图片时，此程序运行出现Bug

### ISSUE THREAD

**Issue by JohnGuoy** [FroyoRab/livp2jpg_eofs#1]
当.livep文件里面包含的是.heic等类型的图片时，此程序不能正常从中提取图片，因为无法识别其中图片格式，提取出来的.jpg文件是0字节的无效文件！

请作者添加新功能：从.livep文件中提取.heic类型的图片，最好能自动识别.livep文件里面包含的是什么格式的图片，然后正确提取出来。

**Comment by FroyoRab** [comment]
可以给我一个包含.heic的样本文件看一下么，我其实不是ios用户。
这个程序其实是依靠Jpg的文件头和文件尾的字节码来提取的，在此之前我都不知道还可能有.heic在内

**Comment by JohnGuoy** [comment]
请问你的邮箱是多少啊，我在你的GitHub主页没有找到你的邮箱。我通过邮箱发你一个包含.heic文件的.livp文件。

**Comment by FroyoRab** [comment]
RabbiTzi0@outlook.com

**Comment by JohnGuoy** [comment]
发你了一个包含.heic文件的.livp文件，在邮箱的附件里。

**Comment by JohnGuoy** [comment]
其实可以用Python的zipfile包，直接解压.livep文件，得到里面的一个图片文件和一个.mov文件。

**Comment by FroyoRab** [comment]
当时写的时候好像尝试过zipfile，当时好像出于什么原因放弃了来着，时间有点长了不记得了

Best,
Froyo M.

发件人: JohnGuoy<mailto:notifications@github.com>
发送时间: 2020年9月19日 20:31
收件人: FroyoRab/livp2jpg<mailto:livp2jpg@noreply.github.com>
抄送: FroyoRab<mailto:RabbiTzi0@outlook.com>; Comment<mailto:comment@noreply.github.com>
主题: Re: [FroyoRab/livp2jpg] 当.livep文件里面包含的是.heic等类型的图片时，此程序运行出现Bug (#1)


其实可以用Python的zipfile包，直接解压.livep文件，得到里面的一个图片文件和一个.mov文件。

―

**Comment by liushuaiQAQ** [comment]
现在还是 0字节的文件

**Comment by JohnGuoy** [comment]
> 现在还是 0字节的文件
请使用以下程序解压.livp文件得到里面的图片文件：
https://github.com/JohnGuoy/unziplivp
至于图片格式可以使用格式工厂转换。

**Comment by FroyoRab** [comment]
歉，之前因为需求和时间一直没进行更改 (并且关于heic当时连格式解析都没有，只有苹果原文，太难啃了
现在对heic进行了支持，在没有pillow和pillow_heif库的情况下，会将heic释放，不会转换。
通过 `pip install pillow pillow_heif` 即可一并进行转换，并且兼容了jpeg。

当然，直接unzip也是很直接的操作~
这个库原意是想不增加其他库的，并且加快速度、减小体积。
但关于heic2jpg，最终还是妥协了。（看了C实现，确实太复杂了，转python好像意义不大
